# Sample Helm values file
port: 8080
image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent
  
service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi